# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 100, 800, 500))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.costView = QtWidgets.QTableView(self.tab1)
        self.costView.setGeometry(QtCore.QRect(0, 0, 800, 331))
        self.costView.setObjectName("costView")
        self.labelDeleteRow = QtWidgets.QLabel(self.tab1)
        self.labelDeleteRow.setGeometry(QtCore.QRect(580, 340, 121, 16))
        self.labelDeleteRow.setObjectName("labelDeleteRow")
        self.deleteRowInput = QtWidgets.QLineEdit(self.tab1)
        self.deleteRowInput.setGeometry(QtCore.QRect(710, 340, 41, 21))
        self.deleteRowInput.setObjectName("deleteRowInput")
        self.pushButtonDeleteRow = QtWidgets.QPushButton(self.tab1)
        self.pushButtonDeleteRow.setGeometry(QtCore.QRect(760, 340, 21, 21))
        self.pushButtonDeleteRow.setObjectName("pushButtonDeleteRow")
        self.pushButtonSaveData = QtWidgets.QPushButton(self.tab1)
        self.pushButtonSaveData.setGeometry(QtCore.QRect(694, 410, 91, 21))
        self.pushButtonSaveData.setObjectName("pushButtonSaveData")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.insertDataButton = QtWidgets.QPushButton(self.tab2)
        self.insertDataButton.setGeometry(QtCore.QRect(550, 320, 75, 23))
        self.insertDataButton.setObjectName("insertDataButton")
        self.inputDate = QtWidgets.QLineEdit(self.tab2)
        self.inputDate.setGeometry(QtCore.QRect(120, 70, 241, 20))
        self.inputDate.setObjectName("inputDate")
        self.inputShop = QtWidgets.QLineEdit(self.tab2)
        self.inputShop.setGeometry(QtCore.QRect(120, 110, 241, 20))
        self.inputShop.setObjectName("inputShop")
        self.inputDescription = QtWidgets.QLineEdit(self.tab2)
        self.inputDescription.setGeometry(QtCore.QRect(120, 150, 241, 20))
        self.inputDescription.setObjectName("inputDescription")
        self.inputCost = QtWidgets.QLineEdit(self.tab2)
        self.inputCost.setGeometry(QtCore.QRect(120, 190, 241, 20))
        self.inputCost.setObjectName("inputCost")
        self.inputEvent = QtWidgets.QLineEdit(self.tab2)
        self.inputEvent.setGeometry(QtCore.QRect(120, 230, 241, 20))
        self.inputEvent.setObjectName("inputEvent")
        self.labelDate = QtWidgets.QLabel(self.tab2)
        self.labelDate.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.labelDate.setObjectName("labelDate")
        self.labelShop = QtWidgets.QLabel(self.tab2)
        self.labelShop.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.labelShop.setObjectName("labelShop")
        self.labelDescriptio = QtWidgets.QLabel(self.tab2)
        self.labelDescriptio.setGeometry(QtCore.QRect(10, 150, 81, 20))
        self.labelDescriptio.setObjectName("labelDescriptio")
        self.labelCost = QtWidgets.QLabel(self.tab2)
        self.labelCost.setGeometry(QtCore.QRect(10, 190, 81, 20))
        self.labelCost.setObjectName("labelCost")
        self.labelEvent = QtWidgets.QLabel(self.tab2)
        self.labelEvent.setGeometry(QtCore.QRect(10, 230, 81, 20))
        self.labelEvent.setObjectName("labelEvent")
        self.labelStar1 = QtWidgets.QLabel(self.tab2)
        self.labelStar1.setGeometry(QtCore.QRect(370, 70, 16, 16))
        self.labelStar1.setObjectName("labelStar1")
        self.labelStar2 = QtWidgets.QLabel(self.tab2)
        self.labelStar2.setGeometry(QtCore.QRect(370, 190, 16, 16))
        self.labelStar2.setObjectName("labelStar2")
        self.labelStar = QtWidgets.QLabel(self.tab2)
        self.labelStar.setGeometry(QtCore.QRect(560, 340, 91, 16))
        self.labelStar.setObjectName("labelStar")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.tabWidget.addTab(self.tab3, "")
        self.userList = QtWidgets.QComboBox(self.centralwidget)
        self.userList.setGeometry(QtCore.QRect(110, 20, 73, 22))
        self.userList.setObjectName("userList")
        self.labelUserSelected = QtWidgets.QLabel(self.centralwidget)
        self.labelUserSelected.setGeometry(QtCore.QRect(14, 20, 91, 20))
        self.labelUserSelected.setObjectName("labelUserSelected")
        self.labelPath = QtWidgets.QLabel(self.centralwidget)
        self.labelPath.setGeometry(QtCore.QRect(60, 50, 31, 20))
        self.labelPath.setObjectName("labelPath")
        self.path = QtWidgets.QLabel(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(110, 50, 681, 20))
        self.path.setObjectName("path")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelDeleteRow.setText(_translate("MainWindow", "Delete row number:"))
        self.pushButtonDeleteRow.setText(_translate("MainWindow", "Ok"))
        self.pushButtonSaveData.setText(_translate("MainWindow", "Save changes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Tab 1"))
        self.insertDataButton.setText(_translate("MainWindow", "PushButton"))
        self.labelDate.setText(_translate("MainWindow", "Date:"))
        self.labelShop.setText(_translate("MainWindow", "Shop:"))
        self.labelDescriptio.setText(_translate("MainWindow", "Description:"))
        self.labelCost.setText(_translate("MainWindow", "Cost:"))
        self.labelEvent.setText(_translate("MainWindow", "Event:"))
        self.labelStar1.setText(_translate("MainWindow", "*"))
        self.labelStar2.setText(_translate("MainWindow", "*"))
        self.labelStar.setText(_translate("MainWindow", "* Mandatory field"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Page"))
        self.labelUserSelected.setText(_translate("MainWindow", "User selected:"))
        self.labelPath.setText(_translate("MainWindow", "Path:"))
        self.path.setText(_translate("MainWindow", "path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

